### ISSUE TITLE
Just Black Font

### ISSUE THREAD

**Issue by FredFleury** [JustCarmen/justblack#10]
Is it possible to adjust the standard header letterfont equal to the font type of the body text ? There is a difference betwween character types of the header and the body text. Body text is more clear, header not.
Or create an menu-option for users to change the font by the users self..

**Comment by JustCarmen** [comment]
You can change the title font in the justblack-css file, located in justblack/css-1.6.2/style.css
search for "header h1"

change this:
>header h1 {	
>	font-family: '@Comfortaa',Verdana,Arial,Helvetica,sans-serif;

to this:
> header h1 {	
>	font-family: Verdana,Arial,Helvetica,sans-serif;

If you don't want the shadow on the font, remove this part to (also in header h1):
>	text-shadow: 2px 2px #000;
>	filter: shadow(color=#000, direction=135, strength=4);

**Comment by FredFleury** [comment]
Great, thanks. Also remove '@Salina' so all fonts on the webtreepages-Justblack are almost similar. Only have to resize the font size and weight.
