### ISSUE TITLE
Just Black Login Welcome text: new account link is not shown

### ISSUE THREAD

**Issue by FredFleury** [JustCarmen/justblack#11]
Option: Administration > Site Configuration > Login > Welcome text on login page > (#4) "Predefined text that states only family members can request a user account"....
This option results in the following text on the login page: in this text is mentioned that one can apply for an user account by clicking on an appropriate link below. THE APPROPRIATE LINK IS NOT SHOWN ON THE PAGE !!!

Welcome to this genealogy website
Access to this site is permitted to family members only.
If you have a user account you can login on this page. If you don’t have a user account, you can apply for one by clicking on the appropriate link below.

After verifying the information you provide, the administrator will either approve or decline your request for an account. You will receive an email when your request is approved.

**Comment by JustCarmen** [comment]
The link is there. See the image below:

![8-1-2015 22-21-07](https://cloud.githubusercontent.com/assets/5641963/5670982/01a2b90e-9785-11e4-9634-940b08a7881b.jpg)
If you don't see the link you must have done something wrong in your account settings. If you have set all trees to private you won't see the link.

**Comment by FredFleury** [comment]
Carmen, your screenshot is correct and shown after a visitor has chosen Log in. Works fine ! But in this case a visitor will first come to/start on  the page with icons above for Homepage, View, Search etc. To avoid non-members to use these options, the must be selected in Admin for members or other. For non-members may be confusing: first getting not working icons on the first page, and only getting the possibility for requesting new account after clicking Log in.

Your screen as shown is displayed only if in Admin the Option Allow Visitors to Request Account is set on NO. If set on YES visitors will see the screens as shown below and in English, instead of in Dutch (as the other screen is, if the option is NO). By the English text, visitors will search for the link to Request new user account, as the text refers "to the link below" that is not shown. Better is to refer to the Log in link !
Thanks and regards, Fred.
![privacy on](https://cloud.githubusercontent.com/assets/7481755/5691058/8d2f6172-98b4-11e4-8d3f-43cb08de13ad.png)

![request account yes](https://cloud.githubusercontent.com/assets/7481755/5691059/977ac4e6-98b4-11e4-86e5-270b1e9750ba.png)

![privacy without](https://cloud.githubusercontent.com/assets/7481755/5691062/9bce7d6c-98b4-11e4-90bb-dc5dfb596aae.png)

**Comment by JustCarmen** [comment]
Fred,

This is not a theme related issue but the way how webtrees works. You won't see the link in any other theme either with the same settings.

You must understand that A user registers for a *TREE*, not for the *SITE*.
If there are no visible trees, it is not possible to register for them, so there is also no link visible.

There are plenty related topics in the webtrees forum, for example this one:
http://www.webtrees.net/index.php/en/forum/help-for-ver-1-6-2/29740-new-user-account-link#49958

**Comment by FredFleury** [comment]
Carmen, thanks. Registering for a Tree not for a site, wasn't clear to me yet. Now it is.
