### ISSUE TITLE
Fancy Imagebar: where to store images

### ISSUE THREAD

**Issue by FredFleury** [JustCarmen/justblack#12]
As I have installed Fancy Imagebar, it is not clear to my where or how to store (in what folder on the server) pictures I want to display. I can nog find an instruction in the instructions for installing the module.

Please let me know....

**Comment by JustCarmen** [comment]
You have posted this issue in the wrong repository. I moved it to: https://github.com/JustCarmen/fancy_imagebar/issues/4
