### ISSUE TITLE
Wheelzoom makes scrolling images difficult.

### ISSUE THREAD

**Issue by terah** [JustCarmen/justblack#15]
Hi, 

The wheel zoom feature in your .js file makes vertical scrolling difficult.

Terry

**Comment by JustCarmen** [comment]
The wheelzoom function is not a specific theme function. It is webtrees default behaviour. The difference is that the JustBlack theme opens a long text readable by default with a vertical scrollbar, while webtrees resize it till it fits in the window (this makes very long texts unreadable at that point). In the default webtrees themes you need to use wheelzoom to make the text larger and readable. Then you need to hold down the mouse while moving the text down to read the entire text. In the JustBlack theme you use the vertical scrollbar for that. In my opinion this gives a better user experience.

You should compare the same text in a webtrees theme with the JustBlack theme and then I am sure you will notice it is easier to read the text from the JustBlack theme.
